GOOSE_CLI_MIN_PRIORITY: 0.8
OLLAMA_HOST: localhost
GOOSE_PROVIDER: ollama
GOOSE_MODE: auto
GOOSE_MODEL: mistral
extensions:
  computercontroller:
    bundled: true
    display_name: Computer Controller
    enabled: true
    name: computercontroller
    timeout: 30
    type: builtin
  developer:
    bundled: true
    display_name: Developer Tools
    enabled: true
    name: developer
    timeout: 30
    type: builtin
  memory:
    bundled: true
    display_name: Memory
    enabled: true
    name: memory
    timeout: 30
    type: builtin

